language: node_js
node_js: "8"

jobs:
  include:
    - stage: test and docs
      script: npm test
    -
      script: npm docs
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true