language: node_js
node_js: "8"

jobs:
  include:
    - stage: install
      script: npm install
    - stage: test
      script: npm test
    - stage: Build Docs
      script: npm docs
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true