language: node_js

jobs:
  include:
    - stage: install
      node_js: "8"
      script: npm install
    - stage: test
      node_js: "8"
      script: npm test
    - stage: Build Docs
      node_js: "8"
      script: npm docs
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true