language: node_js
node_js: '8'
jobs:
  include:
  - stage: test and docs
    script: npm test && npm docs
  - stage: npm release
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: alan.churley@gmail.com
      api_key:
        secure: u4Zf4rXh/lAZHxwm22LCNZNR2ldGH+wubhf04zvzlpuU7VdM5oDyoBSG12TkeI9CLsWVqz5uMqINTFM+Zp5iAg3EWtgC5ldZVcz6I1iuz9zeG/ET6FjTT/Ixv+5D06QvBuUKD16byxPymwih3QNePU8DVwXlP6HB5DihDu8WyPgUuPr9RwXZOKnn9qqLJYOQTuumRFrTdbv8H23htjBVQcFn3E69jO/CVdud/fU+f3JFJK5iLfshk7BAXVK2LhNnQyrJVOnjkXyYyEWG+vgjIfGCRz8t9udCWFk+GSaJwN429GoBtC5QVTDNcIzOKVBIw/lxCLGTTiVWmMKLSfyLAfeiozW8cPptwDst7ohNh97YG0Fn7xaHXcsjcxtRDeueuhb0e4ZQ771KGodzt6s/9c/Fhp5tKvUu6DThnHBjBeI0rlepH/doDWPvpQxKHeQWfWiszD+QiMoErwpjm2KNfqfpgsT+MThmL0KIrMqK1FEkRn7eHlfvwRABuJNee766Cr6PiPmGVy8b0Cf9MNZaQP4P6T/4iFNHJGvdBGPxFKo/4n8P+P5EmZqndhXlvq/5sIM+1qqrtsoQi83zgCsFZugP5t5l5vR5n75OW+8GH9AJHNskkPfuE1ZEXfxvmMZTbSaOjCmmzFFEAmyurh1/V3xI+8GUjC7unP9Lqmh0slA=
      on:
        tags: true
        repo: telegraph/trello-client
